apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'SEU_REPOSITORIO_AQUI'
    targetRevision: HEAD
    path: k8s-config/app-manifests # Onde está o seu Deployment do Nginx
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: producao
  syncPolicy:
    automated:
      prune: true
      selfHeal: true